/**
 *
 * @author scottlee
 */

package minitwitter;


import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;

public class UserView extends javax.swing.JFrame {

    //initializing root node and user
    DefaultMutableTreeNode root;
    Users currentUsername;
    
    //initializing followers list and news feed
    DefaultListModel followerList = new DefaultListModel();
    DefaultListModel newsFeedList = new DefaultListModel();
    
    //UserView accepts a user and a group to determine what user from what group to open their specific user panel
    public UserView(Users user, Groups group) {
        currentUsername = user;
        String username = currentUsername.getUsername();
        root = currentUsername.getRoot();
        
        //store the followers and newsfeed into their corresponding lists to display on the jframe
        followerList = currentUsername.getFollowers();
        newsFeedList = currentUsername.getNewsFeedList();
        
        initComponents();
        
        //show the current user's name on the top left of the frame
        currentUser.setText(username);
        
        //place labels for the follower list and news feed list
        if(followerList.isEmpty()){
            followerList.addElement("Follower List:");
        }
        if(newsFeedList.isEmpty()){
            newsFeedList.addElement("News Feed:");
        }
        
    }
    
    //traverse through the jtree to find the specified user to follow
    //user = current user, node = root node, username = user to follow
    public void findUser(Users user, DefaultMutableTreeNode node, String username) {

        int childCount = node.getChildCount();

        for (int i = 0; i < childCount; i++) {
            
            DefaultMutableTreeNode childNode = (DefaultMutableTreeNode) node.getChildAt(i);
            //if child is a leaf, check if it is the user to follow
            if(childNode.isLeaf()) {
                Users childUser = (Users) childNode.getUserObject();
                if(childUser.toString().equals(username)){
                    //if it is user to follow, add that user to the current user's following list and attach using observer design pattern
                    currentUsername.addFollowers(childUser);
                    childUser.attach(currentUsername);
                    
                }
            }
            //if the node being looked at is a group, then recursively call the method again to look at the leaf nodes within the group
            if(childNode.getAllowsChildren()){
                findUser(currentUsername, childNode, username);
            }
            //if there are no more leafs in the parent node, break out of the method call and continue previous recursive call, or end method if tree only consists of users
            if(i+1 == childCount){
                return;
            }
        }      
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userID = new javax.swing.JTextArea();
        followUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentFollowing = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tweetMessage = new javax.swing.JTextArea();
        postTweet = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        newsFeed = new javax.swing.JList<>();
        currentUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userID.setColumns(20);
        userID.setRows(5);
        jScrollPane1.setViewportView(userID);

        followUser.setText("Follow User");
        followUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUserActionPerformed(evt);
            }
        });

        currentFollowing.setModel(followerList);
        jScrollPane2.setViewportView(currentFollowing);

        tweetMessage.setColumns(20);
        tweetMessage.setRows(5);
        jScrollPane3.setViewportView(tweetMessage);

        postTweet.setText("Post Tweet");
        postTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTweetActionPerformed(evt);
            }
        });

        newsFeed.setModel(newsFeedList);
        jScrollPane4.setViewportView(newsFeed);

        currentUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        currentUser.setText("Scott");
        currentUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postTweet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(currentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(followUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(followUser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(currentUser)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postTweet, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void followUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUserActionPerformed
        //find the user and follow them when follow button is clicked
        findUser(currentUsername, root, userID.getText());
        
    }//GEN-LAST:event_followUserActionPerformed

    private void postTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTweetActionPerformed
        //retrieve string from tweet textfield and tweet from current user
        String tweet = tweetMessage.getText();
        currentUsername.tweet(tweet);
    }//GEN-LAST:event_postTweetActionPerformed

    public static void main(String args[]) {
        //no main method needed, as adminview opens the frame
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> currentFollowing;
    private javax.swing.JLabel currentUser;
    private javax.swing.JButton followUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> newsFeed;
    private javax.swing.JButton postTweet;
    private javax.swing.JTextArea tweetMessage;
    private javax.swing.JTextArea userID;
    // End of variables declaration//GEN-END:variables
}
